name = "satyam-residency-website"
main = "server.js"
compatibility_date = "2024-10-01"

[assets]
directory = "dist"

[[d1_databases]]
binding = "DB"
database_name = "hotel-satyam-booking-db"
database_id = "5a00c6dc-70e4-426d-b0e4-de4ccd1137f3"

[ai]
binding = "AI"
