name = "hotel-satyam-booking"
main = "server.js"
compatibility_date = "2024-10-01"

[assets]
directory = "dist"

# TO CONNECT YOUR DATABASE:
# 1. Create a D1 database in the Cloudflare Dashboard
# 2. Uncomment the three lines below and paste your new database_id
[[d1_databases]]
binding = "DB"
database_name = "hotel-satyam-booking-db"
database_id = "5a00c6dc-70e4-426d-b0e4-de4ccd1137f3"
